import os
import torch

#LAUNCH me with TORCH_LOGS="output_code" python lecture_001/triton_torch_generated_square.py 
# to get triton code generated by torch inductor
print(torch.compile(torch.square)(torch.randn(1823, 781, device="cuda")))